# ─────────────────────────────────────────────────────────────────────────────
# deployment.yaml
# Defines how our ML API pods are created, updated, and kept healthy.
#
# ─────────────────────────────────────────────────────────────────────────────

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dock8s-api
  namespace: dock8s-namespace
  labels:
    app: dock8s-api
spec:
  replicas: 1

  selector:
    matchLabels:
      app: dock8s-api

  template:
    metadata:
      labels:
        app: dock8s-api

    spec:

      containers:
        - name: dock8s-api
          image: fraidoonjan/dock8s
          imagePullPolicy: IfNotPresent # Always

          ports:
            - containerPort: 8080

          # Inject ConfigMap values as environment variables
          envFrom:
            - configMapRef:
                name: dock8s-api-config

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"